HelpersExtensionMvc/Models/ErrorViewModel.cs
using System;

namespace HelpersExtensionMvc.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

HelpersExtensionMvc/Models/Tienda.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HelpersExtensionMvc.Models
{
    public class Tienda
    {

        public String NombreTienda { get; set; }

        public int StockDisponible { get; set; }

        public bool Abierta { get; set; }

        public void AbrirTienda()
        {
            this.Abierta = true;
        }

        public void CerrarTienda()
        {
            this.Abierta = false;
        }
    }
}

HelpersExtensionMvc/Controllers/ExtensionsController.cs
using HelpersExtensionMvc.Extensions;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HelpersExtensionMvc.Controllers
{
    public class ExtensionsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Index(String texto)
        {
            String cadenaFormateada = texto.TransformarTexto();
            ViewBag.TextoFormateado = cadenaFormateada;
            return View(); 
        }

    }
}

HelpersExtensionMvc/Controllers/HomeController.cs
using HelpersExtensionMvc.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace HelpersExtensionMvc.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        { 
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

HelpersExtensionMvc/Controllers/TiendaController.cs
using HelpersExtensionMvc.Extensions;
using HelpersExtensionMvc.Helpers;
using HelpersExtensionMvc.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HelpersExtensionMvc.Controllers
{
    public class TiendaController : Controller
    {
        public IActionResult TiendaHelperView()
        {
            Tienda tienda = new Tienda 
            { 
                NombreTienda = "Teclamania", 
                StockDisponible = 50, 
                Abierta = true 
            };

            string datostienda = HelperTienda.GetInfoTienda(tienda);
            ViewBag.DatosTienda = datostienda;
         
            return View();
        }
    }
}

HelpersExtensionMvc/Views/Extensions/Index.cshtml
<form method="post">
    <input type="text" name="texto" placeholder="Texto a formatear" class="form-control"/>
    <br />
    <button type="submit" class="btn btn-success m-2">
        Formatear texto
    </button>
</form>

<h1>
    @ViewBag.TextoFormateado
</h1>

HelpersExtensionMvc/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

HelpersExtensionMvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HelpersExtensionMvc</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">HelpersExtensionMvc</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @*<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>*@

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Tienda" asp-action="TiendaHelperView">Ejemplo de Helpers</a>
                        </li>


                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Extensions" asp-action="Index">Ejemplo de Extensions</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - HelpersExtensionMvc - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

HelpersExtensionMvc/Views/Tienda/TiendaHelperView.cshtml
<h1 class="text-primary">
    @ViewBag.DatosTienda
</h1>